-- -------- TF2_PAULO--------
--
--                    SCRIPT DE REMOÇÃO (DROP)
--
-- Data Criação ...........: 23/05/2024
-- Autor(es) ..............: Paulo Victor Fonseca Sousa
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: TF_2S22_PAULO_SOUSA
--
-- PROJETO => 01 Base de Dados
--         => 17 Tabelas
-- 05/06/2024 => Criação dos 17 drop tables

USE TF_2S22_PAULO_SOUSA;
DROP TABLE IF EXISTS possui;
DROP TABLE IF EXISTS trabalha;
DROP TABLE IF EXISTS FICHADO;
DROP TABLE IF EXISTS FREELANCER;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS telefone;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS telefoneFornecedor;
DROP TABLE IF EXISTS EVENTO;
DROP TABLE IF EXISTS BUFFET;
DROP TABLE IF EXISTS ESPACO;
DROP TABLE IF EXISTS CONTRATO;
DROP TABLE IF EXISTS TIPOCONTRATO;
DROP TABLE IF EXISTS PESSOAJURIDICA;
DROP TABLE IF EXISTS PESSOAFISICA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS telefoneCliente;
