-- -------- <Trabalho Final Tema 2 Sozinho 24> --------
--
--           SCRIPT DE CRIACAO (DDL)
--
-- DATA DE CRIAÇÃO: 16/06/2024
-- BANCO DE DADOS.: MySQL 8.4
-- AUTOR..........: Victor Hugo Rodrigues Guimarães, 211063256
-- BASE DE DADOS..: TF_S24_victorguimaraes
--
-- PROJETO => 01 base de dados 
--         => 25 tabelas
-- 		   => 02 Perfis (role)
-- ------------------------------------

CREATE DATABASE
	IF NOT EXISTS TF_S24_victorguimaraes;
    
use TF_S24_victorguimaraes;

CREATE TABLE ENDERECO (
    idEndereco INT(5) NOT NULL AUTO_INCREMENT,
    logradouro VARCHAR(20) NOT NULL,
    numero INT(3) NOT NULL,
    cep VARCHAR(9) NOT NULL,
    CONSTRAINT ENDERECO_PK PRIMARY KEY (idEndereco)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE FUNCAO (
    idFuncao INT(5) NOT NULL AUTO_INCREMENT,
    nomeFuncao VARCHAR(20) NOT NULL,
    valorDiaria DECIMAL(10,2) NOT NULL,
    CONSTRAINT FUNCAO_PK PRIMARY KEY (idFuncao)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE GRAUESCOLARIDADE (
    idGrauEscolaridade INT(5) NOT NULL AUTO_INCREMENT,
    nomeGrauEscolaridade VARCHAR(50) NOT NULL,
    CONSTRAINT GRAUESCOLARIDADE_PK PRIMARY KEY (idGrauEscolaridade)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE INFRACAO (
    idInfracao INT(5) NOT NULL AUTO_INCREMENT,
    nomeInfracao VARCHAR(20) NOT NULL,
    gravidadeInfracao INT(2) NOT NULL,
    CONSTRAINT INFRACAO_PK PRIMARY KEY (idInfracao)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE CATEGORIA (
    idCategoria INT(5) NOT NULL AUTO_INCREMENT,
    nomeCategoria VARCHAR(50) NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (idCategoria)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE FORMAPAGAMENTO (
    idFormaPagamento INT(5) NOT NULL AUTO_INCREMENT,
    nomeFormaPagamento VARCHAR(50) NOT NULL,
    CONSTRAINT FORMAPAGAMENTO_PK PRIMARY KEY (idFormaPagamento)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE TIPOITEM (
	idTipoItem INT(5) NOT NULL AUTO_INCREMENT,
    nomeTipoItem VARCHAR(20) NOT NULL,
    CONSTRAINT TIPOITEM_PK PRIMARY KEY (idTipoItem)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE MATERIAPRIMA (
    idMateriaPrima INT(5) NOT NULL AUTO_INCREMENT,
    nomeMateriaPrima VARCHAR(20) NOT NULL,
    quantidadeEstoque INT(2) NOT NULL,
    CONSTRAINT MATERIAPRIMA_PK PRIMARY KEY (idMateriaPrima)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE DECORACAO (
    idDecoracao INT(5) NOT NULL AUTO_INCREMENT,
    descricaoDecoracao VARCHAR(50) NOT NULL,
    valorDecoracao DECIMAL(10,2) NOT NULL,
    CONSTRAINT DECORACAO_PK PRIMARY KEY (idDecoracao)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE FORNECEDOR (
    idFornecedor INT(5) NOT NULL AUTO_INCREMENT,
    chavePIX VARCHAR(100) NOT NULL,
    nomeFornecedor VARCHAR(20) NOT NULL,
    enderecoFornecedor INT(5) NOT NULL,
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (idFornecedor),
    CONSTRAINT FORNECEDOR_ENDERECO_FK FOREIGN KEY (enderecoFornecedor) REFERENCES ENDERECO (idEndereco) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE ITEM (
    idItem INT(5) NOT NULL AUTO_INCREMENT,
    nomeItem VARCHAR(20) NOT NULL,
    valorItem DECIMAL(10,2) NOT NULL,
    tipo INT(5) NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (idItem),
    CONSTRAINT ITEM_TIPOITEM_FK FOREIGN KEY (tipo) REFERENCES TIPOITEM (idTipoItem) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE PESSOA (
    cpf VARCHAR(11) NOT NULL,
    nomePessoa VARCHAR(100) NOT NULL,
    enderecoPessoa INT(5) NOT NULL,
    CONSTRAINT PESSOA_PK PRIMARY KEY (cpf)
)ENGINE = InnoDB;

CREATE TABLE CLIENTE (
	cpf VARCHAR(11) NOT NULL,
    emailCliente VARCHAR(100) NOT NULL,
    indicacao VARCHAR(11),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (cpf),
    CONSTRAINT CLIENTE_CLIENTE_FK FOREIGN KEY (indicacao) REFERENCES CLIENTE (cpf) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT CLIENTE_PESSOA_FK FOREIGN KEY (cpf) REFERENCES PESSOA (cpf) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE EMPRESA (
    cnpj VARCHAR(18) NOT NULL,
    nomeFantasia VARCHAR(50) NOT NULL,
    enderecoEmpresa INT(5) NOT NULL,
    categoriaEmpresa INT(5) NOT NULL,
    representante VARCHAR(11) NOT NULL,
    CONSTRAINT EMPRESA_UK UNIQUE (cnpj),
    CONSTRAINT EMPRESA_ENDERECO_FK FOREIGN KEY (enderecoEmpresa) REFERENCES ENDERECO (idEndereco) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT EMPRESA_CATEGORIA_FK FOREIGN KEY (categoriaEmpresa) REFERENCES CATEGORIA (idCategoria) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT EMPRESA_CLIENTE_FK FOREIGN KEY (representante) REFERENCES CLIENTE (cpf) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE FUNCIONARIO (
    cpf VARCHAR(11) NOT NULL,
    chavePIX VARCHAR(100) NOT NULL,
    agencia VARCHAR(6) NOT NULL,
    conta VARCHAR(8) NOT NULL,
    funcao INT(5) NOT NULL,
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (cpf),
    CONSTRAINT FUNCIONARIO_PESSOA_FK FOREIGN KEY (cpf) REFERENCES PESSOA (cpf) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FUNCIONARIO_FUNCAO_FK FOREIGN KEY (funcao) REFERENCES FUNCAO (idFuncao) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE FIXO (
    ctps VARCHAR(12) NOT NULL,
    grauEscolaridade INT(5) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    CONSTRAINT FIXO_UK UNIQUE (ctps),
    CONSTRAINT FIXO_GRAUESCOLARIDADE_FK FOREIGN KEY (grauEscolaridade) REFERENCES GRAUESCOLARIDADE (idGrauEscolaridade) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FIXO_FUNCIONARIO_FK FOREIGN KEY (cpf) REFERENCES FUNCIONARIO (cpf) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE FREELANCER (
    cpf VARCHAR(11) NOT NULL,
    nota INT(1) NOT NULL,
    CONSTRAINT FREELANCER_FUNCIONARIO_FK FOREIGN KEY (cpf) REFERENCES FUNCIONARIO (cpf) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE EVENTO (
    idEvento INT(5) NOT NULL AUTO_INCREMENT,
    dtEvento DATE NOT NULL,
    hora TIME NOT NULL,
    quantidadePessoas INT(3) NOT NULL,
    decoracao INT(5) NOT NULL,
    cliente VARCHAR(11) NOT NULL,
    enderecoEvento INT(5) NOT NULL,
    CONSTRAINT EVENTO_PK PRIMARY KEY (idEvento),
    CONSTRAINT EVENTO_DECORACAO_FK FOREIGN KEY (decoracao) REFERENCES DECORACAO (idDecoracao) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT EVENTO_CLIENTE_FK FOREIGN KEY (cliente) REFERENCES CLIENTE (cpf) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT EVENTO_ENDERECO_FK FOREIGN KEY (enderecoEvento) REFERENCES ENDERECO (idEndereco) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE CONTRATO (
    idContrato INT(5) NOT NULL AUTO_INCREMENT,
    evento INT(5) NOT NULL,
    formaPagamento INT(5) NOT NULL,
    valorContrato DECIMAL(10,2) NOT NULL,
    CONSTRAINT CONTRATO_PK PRIMARY KEY (idContrato),
    CONSTRAINT CONTRATO_EVENTO_FK FOREIGN KEY (evento) REFERENCES EVENTO (idEvento) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT CONTRATO_FORMAPAGAMENTO_FK FOREIGN KEY (formaPagamento) REFERENCES FORMAPAGAMENTO (idFormaPagamento) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE TRABALHO (
    idEvento INT(5) NOT NULL,
    idFuncionario VARCHAR(11) NOT NULL,
    idInfracao INT(5),
    CONSTRAINT TRABALHO_PK PRIMARY KEY (idEvento, idFuncionario),
    CONSTRAINT TRABALHO_EVENTO_FK FOREIGN KEY (idEvento) REFERENCES EVENTO (idEvento) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT TRABALHO_FUNCIONARIO_FK FOREIGN KEY (idFuncionario) REFERENCES FUNCIONARIO (cpf) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT TRABALHO_INFRACAO_FK FOREIGN KEY (idInfracao) REFERENCES INFRACAO (idInfracao) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE telefoneFornecedor (
    fornecedor INT(5) NOT NULL,
    telefoneFornecedor VARCHAR(15) NOT NULL,
    CONSTRAINT telefoneFornecedor_UK UNIQUE (telefone),
    CONSTRAINT telefoneFornecedor_FORNECEDOR_FK FOREIGN KEY (fornecedor) REFERENCES FORNECEDOR (idFornecedor) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE telefonePessoa (
    pessoa VARCHAR(11) NOT NULL,
    telefonePessoa VARCHAR(15) NOT NULL,
    CONSTRAINT telefonePessoa_UK UNIQUE (telefonePessoa),
    CONSTRAINT telefonePessoa_PESSOA_FK FOREIGN KEY (pessoa) REFERENCES PESSOA (cpf) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE serve (
    idItem INT(5) NOT NULL,
    idEvento INT(5) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    CONSTRAINT serve_ITEM_FK FOREIGN KEY (idItem) REFERENCES ITEM (idItem) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT serve_EVENTO_FK FOREIGN KEY (idEvento) REFERENCES EVENTO (idEvento) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE compoe (
    item INT(5) NOT NULL,
    materiaPrima INT(5) NOT NULL,
    quantidade INT(2) NOT NULL,
    CONSTRAINT compoe_ITEM_FK FOREIGN KEY (item) REFERENCES ITEM (idItem) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT compoe_MATERIAPRIMA_FK FOREIGN KEY (materiaPrima) REFERENCES MATERIAPRIMA (idMateriaPrima) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE fornece (
    fornecedor INT(5) NOT NULL,
    materiaPrima INT(5) NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_fornece_1 FOREIGN KEY (fornecedor) REFERENCES FORNECEDOR (idFornecedor) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FK_fornece_2 FOREIGN KEY (materiaPrima) REFERENCES MATERIAPRIMA (idMateriaPrima) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;