-- -------- < TRABALHO FINAL - TEMA 2 - BUFFET > --------
--
--                    SCRIPT DE CRIACAO (DDL)
--
-- Data Criacao ...........: 08/06/2024
-- Autor(es) ..............: Ryan Salles
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: TF_2S3_ryansalles
--
-- 
-- PROJETO => 01 Base de Dados
--         => 21 Tabelas
--         => 04 Perfis (role)
--         => 08 Usuarios
--  
-- Ultimas Alterações
--      07/06/24
--          * Criação do primeiro script físico
--      08/06/24
-- 			* adição de tabelas FORNECEDOR, TELEFONEFORNECEDOR, EMAILFORNECEDOR,
-- 				e FORNECIMENTO com seus respectivos relacionamentos
--          * Padronização dos nomes das CONSTRAINTS
--          * Alteração das tabelas MENU e INGREDIENTE para incluir um nome em cada
-- 			* Adição manual de ON UPDATE CASCADE para CONSTRAINTS de FK
-- ---------------------------------------------------------

CREATE DATABASE IF NOT EXISTS TF_2S3_ryansalles;

use TF_2S3_ryansalles;

CREATE TABLE DEPARTAMENTO (
    idDepartamento BIGINT NOT NULL AUTO_INCREMENT,
    nomeDepartamento VARCHAR(128) NOT NULL,
    CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY (idDepartamento)
)ENGINE=INNODB AUTO_INCREMENT = 1;

CREATE TABLE CLIENTE (
    identidadeCliente varchar(32) NOT NULL,
    nome varchar(32) NOT NULL, 
    CONSTRAINT CLIENTE_PK PRIMARY KEY (identidadeCliente)
)ENGINE=INNODB;

CREATE TABLE EMAILCLIENTE (
    email VARCHAR(256) NOT NULL,
    identidadeCliente varchar(32) NOT NULL,
    CONSTRAINT EMAILCLIENTE_PK PRIMARY KEY (email),
    CONSTRAINT EMAILCLIENTE_CLIENTE_FK FOREIGN KEY (identidadeCliente) REFERENCES CLIENTE (identidadeCliente) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE TELEFONECLIENTE (
    numero VARCHAR(32) NOT NULL,
    identidadeCliente varchar(32) NOT NULL,
    CONSTRAINT TELEFONECLIENTE_PK PRIMARY KEY (numero),
    CONSTRAINT TELEFONECLIENTE_CLIENTE_FK FOREIGN KEY (identidadeCliente) REFERENCES CLIENTE (identidadeCliente) ON DELETE RESTRICT ON UPDATE CASCADE
    
)ENGINE=INNODB;

CREATE TABLE FUNCIONARIO (
    cpfFuncionario varchar(32) NOT NULL,
    nomeFuncionario VARCHAR(256) NOT NULL,
    tituloFuncionario varchar(32) NOT NULL,
    carteiraFuncionario varchar(32) NOT NULL,
    certidaoFuncionario varchar(32) NOT NULL,
    grauFuncionario varchar(32) NOT NULL,
    idDepartamento BIGINT NOT NULL,
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (cpfFuncionario),
    CONSTRAINT FUNCIONARIO_DEPARTAMENTO_FK FOREIGN KEY (idDepartamento) REFERENCES DEPARTAMENTO (idDepartamento) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE EMAILFUNCIONARIO (
    email VARCHAR(256) NOT NULL,
    cpfFuncionario varchar(32) NOT NULL,
    CONSTRAINT EMAILFUNCIONARIO_PK PRIMARY KEY (email),
    CONSTRAINT EMAILFUNCIONARIO_FUNCIONARIO_FK FOREIGN KEY (cpfFuncionario) REFERENCES FUNCIONARIO (cpfFuncionario) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE TELEFONEFUNCIONARIO (
    numero VARCHAR(32) NOT NULL,
    cpfFuncionario varchar(32) NOT NULL,
    CONSTRAINT TELEFONEFUNCIONARIO PRIMARY KEY (numero),
    CONSTRAINT TELEFONEFUNCIONARIO_FUNCIONARIO_FK FOREIGN KEY (cpfFuncionario) REFERENCES FUNCIONARIO (cpfFuncionario) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE CONTRATO (
    idContrato BIGINT NOT NULL AUTO_INCREMENT,
    tipoContrato BIGINT NOT NULL,
    dataContrato DATETIME NOT NULL,
    estadoContrato VARCHAR(2) NOT NULL,
    cidadeContrato VARCHAR(64) NOT NULL,
    bairroContrato VARCHAR(64) NOT NULL,
    ruaContrato VARCHAR(64) NOT NULL,
    numeroContrato INT NOT NULL,
    valorContrato FLOAT(10, 2) NOT NULL,
    identidadeCliente varchar(32) NOT NULL,
    cpfFuncionario varchar(32) NOT NULL,
    CONSTRAINT CONTRATO_PK PRIMARY KEY (idContrato),
    CONSTRAINT CONTRATO_CLIENTE_FK FOREIGN KEY (identidadeCliente) REFERENCES CLIENTE (identidadeCliente) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT CONTRATO_FUNCIONARIO_FK FOREIGN KEY (cpfFuncionario) REFERENCES FUNCIONARIO (cpfFuncionario) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB AUTO_INCREMENT = 1;

CREATE TABLE EQUIPE (
    idEquipe BIGINT NOT NULL,
    nome VARCHAR(128) NOT NULL,
    idContrato BIGINT NOT NULL,
    CONSTRAINT EQUIPE_PK PRIMARY KEY (idEquipe),
    CONSTRAINT EQUIPE_CONTRATO_FK FOREIGN KEY (idContrato) REFERENCES CONTRATO(idContrato) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE FREELANCER (
    cpfFreelancer VARCHAR(32) NOT NULL,
    nomeFreelancer VARCHAR(256) NOT NULL,
    categoriaFreelancer VARCHAR(32) NOT NULL,
    estrelasFreelancer INT NOT NULL,
    CONSTRAINT FREELANCER_PK PRIMARY KEY (cpfFreelancer)
)ENGINE=INNODB;

CREATE TABLE EMAILFREELANCER (
    email VARCHAR(256) NOT NULL,
    cpfFreelancer VARCHAR(32) NOT NULL,
    CONSTRAINT EMAILFREELANCER_PK PRIMARY KEY (email),
    CONSTRAINT EMAILFREELANCER_FREELANCER_FK FOREIGN KEY (cpfFreelancer) REFERENCES FREELANCER (cpfFreelancer) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE TELEFONEFREELANCER (
    numero VARCHAR(32) NOT NULL,
    cpfFreelancer VARCHAR(32),
    CONSTRAINT TELEFONEFREELANCER_PK PRIMARY KEY (numero),
    CONSTRAINT TELEFONEFREELANCER_FREELANCER_FK FOREIGN KEY (cpfFreelancer) REFERENCES FREELANCER (cpfFreelancer) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE EQUIPEFREELANCER (
    cpfFreelancer VARCHAR(32) NOT NULL,
    idEquipe BIGINT NOT NULL,
    CONSTRAINT EQUIPEFREELANCER_FREELANCER_FK FOREIGN KEY (cpfFreelancer) REFERENCES FREELANCER (cpfFreelancer) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT EQUIPEFREELANCER_EQUIPE_FK FOREIGN KEY (idEquipe) REFERENCES EQUIPE (idEquipe) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE MENU (
    idMenu BIGINT NOT NULL AUTO_INCREMENT,
    nomeMenu VARCHAR(128) NOT NULL,
    idContrato BIGINT NOT NULL,
    CONSTRAINT MENU_PK PRIMARY KEY (idMenu),
    CONSTRAINT MENU_CONTRATO_FK FOREIGN KEY (idContrato) REFERENCES CONTRATO (idContrato) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB AUTO_INCREMENT = 1;

CREATE TABLE PRATO (
    idPrato BIGINT NOT NULL AUTO_INCREMENT,
    nomePrato VARCHAR(128) NOT NULL,
    idMenu BIGINT NOT NULL,
    CONSTRAINT PRATO_PK PRIMARY KEY (idPrato),
    CONSTRAINT PRATO_MENU_FK FOREIGN KEY (idMenu) REFERENCES MENU (idMenu) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB AUTO_INCREMENT = 1;

CREATE TABLE INGREDIENTE (
    idIngrediente BIGINT NOT NULL AUTO_INCREMENT,
    nomeIngrediente VARCHAR(128) NOT NULL,
    CONSTRAINT INGREDIENTE_PK PRIMARY KEY (idIngrediente)
)ENGINE=INNODB AUTO_INCREMENT = 1;

CREATE TABLE FORNECEDOR (
    idFornecedor BIGINT NOT NULL AUTO_INCREMENT,
    nomeFornecedor VARCHAR(256) NOT NULL,
    estrelasFornecedor INT NOT NULL,
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (idFornecedor)
)ENGINE=INNODB AUTO_INCREMENT = 1;

CREATE TABLE EMAILFORNECEDOR (
    email VARCHAR(256) NOT NULL,
    idFornecedor BIGINT NOT NULL,
    CONSTRAINT EMAILFORNECEDOR_PK PRIMARY KEY (email),
    CONSTRAINT EMAILFORNECEDOR_FORNECEDOR_FK FOREIGN KEY (idFornecedor) REFERENCES FORNECEDOR (idFornecedor) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE TELEFONEFORNECEDOR (
    numero VARCHAR(32) NOT NULL,
    idFornecedor BIGINT NOT NULL,
    CONSTRAINT TELEFONEFORNECEDOR_PK PRIMARY KEY (numero),
    CONSTRAINT TELEFONEFORNECEDOR_FORNECEDOR_FK FOREIGN KEY (idFornecedor) REFERENCES FORNECEDOR (idFornecedor) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE FORNECIMENTO (
    nFiscalFornecimento VARCHAR(64) NOT NULL,
    dataFornecimento DATETIME NOT NULL,
    valorFornecimento FLOAT(10, 2) NOT NULL,
    idFornecedor BIGINT NOT NULL,
    idIngrediente BIGINT NOT NULL,
    CONSTRAINT FORNECIMENTO_PK PRIMARY KEY (nFiscalFornecimento),
    CONSTRAINT FORNECIMENTO_FORNECEDOR_FK FOREIGN KEY (idFornecedor) REFERENCES FORNECEDOR (idFornecedor) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FORNECIMENTO_INGREDIENTE_FK FOREIGN KEY (idIngrediente)REFERENCES INGREDIENTE (idIngrediente) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE PRATOINGREDIENTE (
    idPrato BIGINT NOT NULL,
    idIngrediente BIGINT NOT NULL,
    CONSTRAINT PRATOINGREDIENTE_PRATO_FK FOREIGN KEY (idPrato) REFERENCES PRATO (idPrato) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT PRATOINGREDIENTE_INGREDIENTE_FK FOREIGN KEY (idIngrediente) REFERENCES INGREDIENTE (idIngrediente) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;