-- -------- < TRABALHO FINAL - TEMA 2 - BUFFET > --------
--
--                    SCRIPT FISICO (DDL)
--
-- Data Criacao ...........: 23/06/2024
-- Autor(es) ..............: Paulo Filho, Paulo Sousa, Ryan Salles, Victor Guimaraes
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: TF_2I
--
-- 
-- PROJETO => 01 base de dados 
--         => 19 tabelas
-- 		   => 04 Perfis (role)
--         => 12 Usuários
--  
-- Ultimas Alterações
--      23/06/24
--          * Criação e atualização do script para criação de tabelas 
-- 				conforme requisitos.  
-- ---------------------------------------------------------

CREATE DATABASE 
	IF NOT EXISTS TF_2I;
    
USE TF_2I;

CREATE TABLE ENDERECO (
    idEndereco BIGINT NOT NULL AUTO_INCREMENT,
    logradouro VARCHAR(20) NOT NULL,
    numero INT NOT NULL,
    cep VARCHAR(9) NOT NULL,
    cidade VARCHAR(20),
    estado VARCHAR(2),
    CONSTRAINT ENDERECO_PK PRIMARY KEY (idEndereco)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE PESSOA (
    cpf VARCHAR(11) NOT NULL,
    nomePessoa VARCHAR(128) NOT NULL,
    enderecoPessoa BIGINT NOT NULL,
    CONSTRAINT PESSOA_PK PRIMARY KEY (cpf),
    CONSTRAINT PESSOA_ENDERECO_FK FOREIGN KEY (enderecoPessoa)
        REFERENCES ENDERECO (idEndereco)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE FUNCAOCOLABORADOR (
    idFuncao BIGINT NOT NULL AUTO_INCREMENT,
    nomeFuncao VARCHAR(20) NOT NULL,
    valorDiaria DECIMAL(10,2) NOT NULL,
    CONSTRAINT FUNCAO_PK PRIMARY KEY (idFuncao)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE CLIENTE (
    cpf VARCHAR(11) NOT NULL,
    emailCliente VARCHAR(100) NOT NULL,
    indicacao VARCHAR(11),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (cpf),
    CONSTRAINT CLIENTE_PESSOA_FK FOREIGN KEY (cpf)
        REFERENCES PESSOA (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT CLIENTE_CLIENTE_FK FOREIGN KEY (indicacao)
        REFERENCES CLIENTE (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE EMPRESA (
    cnpj VARCHAR(18) NOT NULL,
    nomeFantasia VARCHAR(128) NOT NULL,
    categoriaEmpresa ENUM('MEI', 'EI', 'Ltda', 'SLU', 'SA') NOT NULL,
    enderecoEmpresa BIGINT NOT NULL,
    representante VARCHAR(11) NOT NULL,
    CONSTRAINT EMPRESA_UK UNIQUE (cnpj),
    CONSTRAINT EMPRESA_ENDERECO_FK FOREIGN KEY (enderecoEmpresa)
        REFERENCES ENDERECO (idEndereco)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT EMPRESA_CLIENTE_FK FOREIGN KEY (representante)
        REFERENCES CLIENTE (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE COLABORADOR (
    cpf VARCHAR(11) NOT NULL,
    chavePIX VARCHAR(100) NOT NULL,
    agencia VARCHAR(6) NOT NULL,
    conta VARCHAR(8) NOT NULL,
    dtNascimento DATE,
    funcao BIGINT NOT NULL,
    CONSTRAINT COLABORADOR_PK PRIMARY KEY (cpf),
    CONSTRAINT COLABORADOR_PESSOA_FK FOREIGN KEY (cpf)
        REFERENCES PESSOA (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT COLABORADOR_FUNCAO_FK FOREIGN KEY (funcao)
        REFERENCES FUNCAOCOLABORADOR (idFuncao)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE FICHADO (
    ctps VARCHAR(12) NOT NULL,
    grauEscolaridade ENUM('FUNDAMENTAL', 'MEDIO', 'SUPERIOR') NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    CONSTRAINT FICHADO_UK UNIQUE (ctps),
    CONSTRAINT FICHADO_COLABORADOR_FK FOREIGN KEY (cpf)
        REFERENCES COLABORADOR (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE FORNECEDOR (
    idFornecedor BIGINT NOT NULL AUTO_INCREMENT,
    chavePIX VARCHAR(100) NOT NULL,
    nomeFornecedor VARCHAR(128) NOT NULL,
    enderecoFornecedor BIGINT NOT NULL,
    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (idFornecedor),
    CONSTRAINT FORNECEDOR_ENDERECO_FK FOREIGN KEY (enderecoFornecedor)
        REFERENCES ENDERECO (idEndereco)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE ALIMENTO (
    idAlimento BIGINT NOT NULL AUTO_INCREMENT,
    nomeAlimento VARCHAR(128) NOT NULL,
    tipoAlimento ENUM("BEBIDA", "ENTRADA", "PRINCIPAL", "SOBREMESA") NOT NULL,
    CONSTRAINT ALIMENTO_PK PRIMARY KEY (idAlimento)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE MATERIAPRIMA (
    idMateriaPrima BIGINT NOT NULL AUTO_INCREMENT,
    nomeMateriaPrima VARCHAR(64) NOT NULL,
    CONSTRAINT MATERIAPRIMA_PK PRIMARY KEY (idMateriaPrima)
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE EVENTO (
    idEvento BIGINT NOT NULL AUTO_INCREMENT,
    dtEvento DATE NOT NULL,
    hora TIME NOT NULL,
    quantidadePessoas INT NOT NULL,
    decoracao VARCHAR(256) NOT NULL,
    cliente VARCHAR(11) NOT NULL,
    enderecoEvento BIGINT NOT NULL,
    CONSTRAINT EVENTO_PK PRIMARY KEY (idEvento),
    CONSTRAINT EVENTO_CLIENTE_FK FOREIGN KEY (cliente)
        REFERENCES CLIENTE (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT EVENTO_ENDERECO_FK FOREIGN KEY (enderecoEvento)
        REFERENCES ENDERECO (idEndereco)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE COLABORADOREVENTO (
    idEvento BIGINT NOT NULL AUTO_INCREMENT,
    idColaborador VARCHAR(11) NOT NULL,
    CONSTRAINT TRABALHO_EVENTO_FK FOREIGN KEY (idEvento)
        REFERENCES EVENTO (idEvento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT TRABALHO_COLABORADOR_FK FOREIGN KEY (idColaborador)
        REFERENCES COLABORADOR (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 1;

CREATE TABLE FREELANCER (
    cpf VARCHAR(11) NOT NULL,
    nota INT NOT NULL,
    CONSTRAINT FREELANCER_COLABORADOR_FK FOREIGN KEY (cpf)
        REFERENCES COLABORADOR (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE TELEFONEPESSOA (
    pessoa VARCHAR(11) NOT NULL,
    telefonePessoa VARCHAR(15) NOT NULL,
    CONSTRAINT telefonePessoa_UK UNIQUE (telefonePessoa),
    CONSTRAINT telefonePessoa_PESSOA_FK FOREIGN KEY (pessoa)
        REFERENCES PESSOA (cpf)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE TELEFONEFORNECEDOR (
    fornecedor BIGINT NOT NULL,
    telefoneFornecedor VARCHAR(15) NOT NULL,
    CONSTRAINT telefoneFornecedor_UK UNIQUE (telefoneFornecedor),
    CONSTRAINT telefoneFornecedor_FORNECEDOR_FK FOREIGN KEY (fornecedor)
        REFERENCES FORNECEDOR (idFornecedor)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE EVENTOALIMENTO (
    idAlimento BIGINT NOT NULL,
    idEvento BIGINT NOT NULL,
    CONSTRAINT serve_ALIMENTO_FK FOREIGN KEY (idAlimento)
        REFERENCES ALIMENTO (idAlimento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT serve_EVENTO_FK FOREIGN KEY (idEvento)
        REFERENCES EVENTO (idEvento)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE ALIMENTOMATERIAPRIMA (
    alimento BIGINT NOT NULL,
    materiaPrima BIGINT NOT NULL,
    quantidadeEstoque INT NOT NULL,
    CONSTRAINT ALIMENTOMATERIAPRIMA_ALIMENTO_FK FOREIGN KEY (alimento)
        REFERENCES ALIMENTO (idAlimento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ALIMENTOMATERIAPRIMA_MATERIAPRIMA_FK FOREIGN KEY (materiaPrima)
        REFERENCES MATERIAPRIMA (idMateriaPrima)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE FORNECEDORMATERIAPRIMA (
    fornecedor BIGINT NOT NULL,
    materiaPrima BIGINT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    CONSTRAINT FORNECEDORMATERIAPRIMA_FORNECEDOR_FK FOREIGN KEY (fornecedor)
        REFERENCES FORNECEDOR (idFornecedor)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT FORNECEDORMATERIAPRIMA_MATERIAPRIMA_FK FOREIGN KEY (materiaPrima)
        REFERENCES MATERIAPRIMA (idMateriaPrima)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;

CREATE TABLE CONTRATO (
    idContrato BIGINT NOT NULL,
    evento BIGINT NOT NULL,
    formaPagamento ENUM('BOLETO', 'PIX', 'CREDITO', 'DEBITO') NOT NULL,
    valorContrato DECIMAL(10,2) NOT NULL,
    tipoContrato ENUM('ESPACO', 'BUFFETESPACO', 'BUFFET'),
    CONSTRAINT CONTRATO_PK PRIMARY KEY (idContrato),
    CONSTRAINT CONTRATO_EVENTO_PK FOREIGN KEY (evento)
        REFERENCES EVENTO (idEvento)
        ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE = InnoDB;